### ISSUE TITLE
cannot find symbol creativecreatorormaybenot.wakelock.WakelockPlugin()

### ISSUE THREAD

**Issue by Arthur-Kamau** [creativecreatorormaybenot/wakelock#35]
Linux version :  20.04
## Flutter doctor:
![Screenshot from 2020-07-31 11-28-50](https://user-images.githubusercontent.com/30284230/89017310-c70ba780-d322-11ea-91dd-28fc4fac089d.png)

## What i have tried.
1. delete pubspeck.lock file and run flutter pub get.
2. cd android && ./gradlew clean assembleDebug && ./gradlew build --refresh-dependencies
this throws this error  
![Screenshot from 2020-07-31 11-45-17](https://user-images.githubusercontent.com/30284230/89017889-abed6780-d323-11ea-993a-65145de47d4a.png)

3. remove  wakelock from  {path_to_flutter_installation}/flutter/.pub-cache/hosted/pub.dartlang.org &&  rm -rfv  wakelock-0.1.4+2/  then   flutter pub get.

## Error.
![Screenshot from 2020-07-31 11-39-25](https://user-images.githubusercontent.com/30284230/89017245-acd1c980-d322-11ea-97dd-132df68f83a8.png)

**Comment by creativecreatorormaybenot** [comment]
Thank you for reporting this issue 👍🏼 This error seems weird 😶

1. Did you try to run `flutter clean`?
2. What version of Flutter are you using?

**Comment by Arthur-Kamau** [comment]
yes, i did.
flutter v 1.17.2 (Image above), even after upgrading to 1.17.5.

**Comment by creativecreatorormaybenot** [comment]
Do you have multiple projects in your file tree? It seems like the plugin registrant is not setup.

**Comment by Arthur-Kamau** [comment]
In the end i did a reinstall of the operating system.
It solved my problem.
