### ISSUE TITLE
Errors during build process on Microsoft App Center

### ISSUE THREAD

**Issue by tnaseem** [creativecreatorormaybenot/wakelock#32]
I'm getting errors during the build process on Microsoft's App Center with wakelock 0.1.4+1.

The log snippet shows this:

```
> Configure project :
Resolved com.android.tools.build:gradle:3.5.0 in :classpath 
Resolved org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 in :classpath 
Project wakelock at : is either no Android app project or build version has not been set to override. Skipping...
Resolved org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50 in :releaseRuntimeClasspath 
Resolved io.flutter:flutter_embedding_release:1.0.0-ee76268252c22f5c11e82a7b87423ca3982e51a7 in :releaseCompileClasspath 
Resolved org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50 in :releaseCompileClasspath 
Resolved org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50 in :releaseCompileClasspath 
Resolved org.jetbrains.kotlin:kotlin-stdlib:1.3.50 in :releaseCompileClasspath 
Resolved org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50 in :releaseCompileClasspath 
Resolved org.jetbrains:annotations:13.0 in :releaseCompileClasspath 
Resolved org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.50 in :kotlinCompilerClasspath 
Resolved com.android.tools.lint:lint-gradle:26.5.0 in :lintClassPath 

> Task :assembleAarRelease UP-TO-DATE
> Task :preBuild UP-TO-DATE
> Task :preReleaseBuild UP-TO-DATE
> Task :compileReleaseAidl NO-SOURCE
> Task :compileReleaseRenderscript NO-SOURCE
> Task :checkReleaseManifest
> Task :generateReleaseBuildConfig
> Task :generateReleaseResValues
> Task :generateReleaseResources
> Task :packageReleaseResources
> Task :mergeReleaseShaders
> Task :compileReleaseShaders
> Task :generateReleaseAssets
> Task :packageReleaseAssets
> Task :packageReleaseRenderscript NO-SOURCE
> Task :processReleaseJavaRes NO-SOURCE
> Task :mergeReleaseJniLibFolders
> Task :prepareLintJarForPublish
> Task :parseReleaseLibraryResources
> Task :processReleaseManifest
> Task :mergeReleaseNativeLibs
> Task :stripReleaseDebugSymbols
> Task :transformNativeLibsWithSyncJniLibsForRelease
> Task :generateReleaseRFile

> Task :compileReleaseKotlin FAILED
16 actionable tasks: 16 executed

e: /Users/runner/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+1/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (3, 28): Unresolved reference: NonNull
e: /Users/runner/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+1/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (16, 36): Unresolved reference: NonNull
e: /Users/runner/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+1/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (46, 30): Unresolved reference: NonNull
e: /Users/runner/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+1/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (46, 57): Unresolved reference: NonNull
e: /Users/runner/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+1/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (62, 38): Unresolved reference: NonNull

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

The plugin wakelock could not be built due to the issue above.

##[error]The process '/bin/bash' failed with exit code 1
##[error]Bash failed with error: The process '/bin/bash' failed with exit code 1
```

I had a similar issue with the assets_audio_player plugin and the author was quick to apply a fix. Details here:
https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/266

**Comment by tnaseem** [comment]
Exactly the same build failure on Codemagic too:

```
== Building for Android ==

> /usr/local/bin/flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...                        
WARNING: [Processor] Library '/Users/builder/.gradle/caches/modules-2/files-2.1/com.google.android.exoplayer/exoplayer-ui/2.11.4/8be1e4b0aba76de3d8216633c8d9d1625fda2acf/exoplayer-ui-2.11.4.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

 Example of androidX reference: 'androidx/core/app/NotificationCompat$Builder'

 Example of support library reference: 'android/support/v4/media/session/MediaSessionCompat$Token'

Note: /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.11/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.11+2/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.



FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':app:lintVitalRelease'.

> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.

   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.

      > Execution failed for JetifyTransform: /Users/builder/clone/whitu/build/app/intermediates/flutter/debug/libs.jar.

         > Failed to transform '/Users/builder/clone/whitu/build/app/intermediates/flutter/debug/libs.jar' using Jetifier. Reason: FileNotFoundException, message: /Users/builder/clone/whitu/build/app/intermediates/flutter/debug/libs.jar (No such file or directory). (Run with --stacktrace for more details.)

           Please file a bug at http://issuetracker.google.com/issues/new?component=460323.



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 9m 9s
Running Gradle task 'assembleRelease'...                          561.7s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin assets_audio_player...
Running Gradle task 'assembleAarRelease'...                       142.9s (!)
✓ Built build/app/outputs/repo.
Building plugin assets_audio_player_web...
Running Gradle task 'assembleAarRelease'...                        49.1s
✓ Built build/app/outputs/repo.
Building plugin flutter_local_notifications...
Running Gradle task 'assembleAarRelease'...                        14.0s
✓ Built build/app/outputs/repo.
Building plugin package_info...
Running Gradle task 'assembleAarRelease'...                        19.4s
✓ Built build/app/outputs/repo.
Building plugin path_provider...
Running Gradle task 'assembleAarRelease'...                         3.9s
✓ Built build/app/outputs/repo.
Building plugin sqflite...
Running Gradle task 'assembleAarRelease'...                        20.0s
✓ Built build/app/outputs/repo.
Building plugin url_launcher...
Running Gradle task 'assembleAarRelease'...                        18.2s
✓ Built build/app/outputs/repo.
Building plugin video_player...
Running Gradle task 'assembleAarRelease'...                        35.5s
✓ Built build/app/outputs/repo.
Building plugin wakelock...
Running Gradle task 'assembleAarRelease'...                        13.0s
> Task :assembleAarRelease UP-TO-DATE
> Task :preBuild UP-TO-DATE
> Task :preReleaseBuild UP-TO-DATE
> Task :compileReleaseAidl NO-SOURCE
> Task :compileReleaseRenderscript NO-SOURCE
> Task :checkReleaseManifest
> Task :generateReleaseBuildConfig
> Task :generateReleaseResValues
> Task :generateReleaseResources
> Task :packageReleaseResources
> Task :mergeReleaseShaders
> Task :compileReleaseShaders
> Task :generateReleaseAssets
> Task :packageReleaseAssets
> Task :packageReleaseRenderscript NO-SOURCE
> Task :processReleaseJavaRes NO-SOURCE
> Task :mergeReleaseJniLibFolders
> Task :prepareLintJarForPublish
> Task :parseReleaseLibraryResources
> Task :mergeReleaseNativeLibs
> Task :stripReleaseDebugSymbols
> Task :transformNativeLibsWithSyncJniLibsForRelease
> Task :processReleaseManifest
> Task :generateReleaseRFile

> Task :compileReleaseKotlin FAILED
16 actionable tasks: 16 executed

e: /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+1/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (3, 28): Unresolved reference: NonNull
e: /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+1/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (16, 36): Unresolved reference: NonNull
e: /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+1/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (46, 30): Unresolved reference: NonNull
e: /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+1/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (46, 57): Unresolved reference: NonNull
e: /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+1/android/src/main/kotlin/creativecreatorormaybenot/wakelock/WakelockPlugin.kt: (62, 38): Unresolved reference: NonNull

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

The plugin wakelock could not be built due to the issue above.


Build failed :|
Failed to build for Android
```

**Comment by creativecreatorormaybenot** [comment]
Never heard of Microsoft App Center, but I can take a look at the linked PR.

If you need this asap, you could also open a PR to fix it yourself 👌🏽

**Comment by tnaseem** [comment]
It was happening on Codemagic too. Anyway, I have found a workaround which seems to get around the issue. Not a solution, but at least it doesn't fail.

I added:
'''
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
'''

To the `android/app/build.gradle` file.

This tip was from a post on [StackOverflow](https://stackoverflow.com/questions/49286268/error-execution-failed-for-task-app-lintvitalrelease-any-one-can-solve-it).


This tip was from a post on [StackOverflow](https://stackoverflow.com/questions/49286268/error-execution-failed-for-task-app-lintvitalrelease-any-one-can-solve-it).

**Comment by creativecreatorormaybenot** [comment]
@tnaseem Can you try again using `wakelock: 0.1.4+2`?

**Comment by tnaseem** [comment]
That fixed it! Many thanks :)

I removed my changes above and it worked with wavelock 0.1.4+2.

Still getting build errors, but these seem to be internal to flutter itself! So, I'll stick the lintOptions above back in. It never ends...

wavelock is fine though! Thanks for your help.
