### ISSUE TITLE
There is problem in WAKELOCK dependency with Xcode 12.

### ISSUE THREAD

**Issue by waqaskhan409** [creativecreatorormaybenot/wakelock#38]
Third-party dependency uses WAKELOCK dependency which causes failure in Xcode 12, Can you please solve this asap?

Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:1:
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.h:3:38: error: no type or protocol named 'FlutterPlugin'
    @interface WakelockPlugin : NSObject<FlutterPlugin>
                                         ^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:4:41: error: no type or protocol named 'FlutterPluginRegistrar'
    + (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar {
                                            ^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:12:27: error: expected a type
    - (void)handleMethodCall:(FlutterMethodCall*)call result:(FlutterResult)result {
                              ^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:12:59: error: expected a type
    - (void)handleMethodCall:(FlutterMethodCall*)call result:(FlutterResult)result {
                                                              ^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:5:3: error: use of undeclared identifier 'FlutterMethodChannel'
      FlutterMethodChannel* channel = [FlutterMethodChannel
      ^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:5:25: error: use of undeclared identifier 'channel'
      FlutterMethodChannel* channel = [FlutterMethodChannel
                            ^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:5:36: error: use of undeclared identifier 'FlutterMethodChannel'
      FlutterMethodChannel* channel = [FlutterMethodChannel
                                       ^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:9:14: error: no visible @interface for 'NSObject' declares the selector 'addMethodCallDelegate:channel:'
      [registrar addMethodCallDelegate:instance channel:channel];
       ~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:13:39: error: property 'method' not found on object of type '__strong id'
      if ([@"toggle" isEqualToString:call.method]) {
                                          ^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:14:29: error: property 'arguments' not found on object of type '__strong id'
        NSNumber *enable = call.arguments[@"enable"];
                                ^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:18:13: error: called object type 'id' is not a function or function pointer
          result(nil);
          ~~~~~~^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:21:13: error: called object type 'id' is not a function or function pointer
          result(nil);
          ~~~~~~^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:23:49: error: property 'method' not found on object of type '__strong id'
      } else if ([@"isEnabled" isEqualToString:call.method]) {
                                                    ^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:24:11: error: called object type 'id' is not a function or function pointer
        result([NSNumber numberWithBool:[[UIApplication sharedApplication] isIdleTimerDisabled]]);
        ~~~~~~^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:26:11: error: called object type 'id' is not a function or function pointer
        result(FlutterMethodNotImplemented);
        ~~~~~~^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:9:53: error: use of undeclared identifier 'channel'
      [registrar addMethodCallDelegate:instance channel:channel];
                                                        ^
    /Users/waqas/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.1.4+2/ios/Classes/WakelockPlugin.m:26:12: error: use of undeclared identifier 'FlutterMethodNotImplemented'
        result(FlutterMethodNotImplemented);

**Comment by creativecreatorormaybenot** [comment]
Does this still.happen with `wakelock: ^0.2.0`?

**Comment by waqaskhan409** [comment]
let me review

**Comment by creativecreatorormaybenot** [comment]
@waqaskhan409 Sure! Make sure that you use `wakelock: ^0.2.0+1` because that fixes a different iOS build issue.

**Comment by bazinac** [comment]
Hey, for me it works ok with ` wakelock: ^0.2.0+1`. XCode 12 + iPhone SE 2020 with iOS 14. Thank for the good work!

**Comment by waqaskhan409** [comment]
It is working!, Thanks alot @creativecreatorormaybenot
